export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const REQUEST_PLANET_DETAIL = 'REQUEST_PLANET_DETAIL';
export const RECEIVE_PLANET_DETAIL = 'RECEIVE_PLANET_DETAIL';
